{
 "title": "PI Quality Metrics (InfluxDB2)",
 "description": "This leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses.\n\nhttps://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "time": { "from": "2020-09-15T23:00:00.000Z", "to": "2020-12-16T23:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Cross PI Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commits over PI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> set(key: \"_field\",value: \"PI8 (2020-09-16)\")\n  |> yield(name: \"PI8\")\n\n\ntime1PI7 = uint(v: 2020-06-16T00:00:00Z)\ntime2PI7 = uint(v: 2020-09-16T00:00:00Z)\ndurPI7 = duration(v: time2PI7 - time1PI7)\n\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> set(key: \"_field\",value: \"PI7 (2020-06-16)\")\n  |> timeShift(duration: durPI7, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"PI7\")\n\n\ntime1PI6 = uint(v: 2020-03-16T00:00:00Z)\ntime2PI6 = uint(v: 2020-09-16T00:00:00Z)\ndurPI6 = duration(v: time2PI6 - time1PI6)\n\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> set(key: \"_field\",value: \"PI6 (2020-03-16)\")\n  |> timeShift(duration: durPI6, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"PI6\")\n\n\ntime1PI5 = uint(v: 2019-12-15T00:00:00Z)\ntime2PI5 = uint(v: 2020-09-16T00:00:00Z)\ndurPI5 = duration(v: time2PI5 - time1PI5)\n\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> set(key: \"_field\",value: \"PI5 (2019-12-15)\")\n  |> timeShift(duration: durPI5, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"PI5\")\n\n\ntime1PI4 = uint(v: 2019-09-14T00:00:00Z)\ntime2PI4 = uint(v: 2020-09-16T00:00:00Z)\ndurPI4 = duration(v: time2PI4 - time1PI4)\n\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> set(key: \"_field\",value: \"PI4 (2019-09-14)\")\n  |> timeShift(duration: durPI4, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"PI4\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commits with Jira",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nt1PI4 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2PI4 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nPI4 = join(tables: {t1: t1PI4, t2: t2PI4 }, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> set(key: \"_field\",value: \"PI4\")\n  |> drop(columns:[\"default\"])\n\n\nt1PI5 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2PI5 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nPI5 = join(tables: {t1: t1PI5, t2: t2PI5 }, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> set(key: \"_field\",value: \"PI5\")\n  |> drop(columns:[\"default\"])\n\n\nt1PI6 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2PI6 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nPI6 = join(tables: {t1: t1PI6, t2: t2PI6 }, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> set(key: \"_field\",value: \"PI6\")\n  |> drop(columns:[\"default\"])\n\n\nt1PI7 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2PI7 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nPI7 = join(tables: {t1: t1PI7, t2: t2PI7 }, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> set(key: \"_field\",value: \"PI7\")\n  |> drop(columns:[\"default\"])\n\n\nt1PI8 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2PI8 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nPI8 = join(tables: {t1: t1PI8, t2: t2PI8 }, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> set(key: \"_field\",value: \"PI8\")\n  |> drop(columns:[\"default\"])\n\n\nunion(tables: [PI4, PI5, PI6, PI7, PI8])\n  |> yield(name: \"jira\")\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PI Commit Lines Changed ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "PI4 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"project\", \"project_id\", \"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"bare\", \"ref\", \"who\", \"branch_name\",\"_measurement\", \"_field\"])\n  |> sum()\n  |> set(key: \"_field\",value: \"PI4\")\n\n\nPI5 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"project\", \"project_id\", \"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"bare\", \"ref\", \"who\", \"branch_name\",\"_measurement\", \"_field\"])\n  |> sum()\n  |> set(key: \"_field\",value: \"PI5\")\n\n\nPI6 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"project\", \"project_id\", \"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"bare\", \"ref\", \"who\", \"branch_name\",\"_measurement\", \"_field\"])\n  |> sum()\n  |> set(key: \"_field\",value: \"PI6\")\n\n\nPI7 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"project\", \"project_id\", \"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"bare\", \"ref\", \"who\", \"branch_name\",\"_measurement\", \"_field\"])\n  |> sum()\n  |> set(key: \"_field\",value: \"PI7\")\n\n\nPI8 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"project\", \"project_id\", \"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"bare\", \"ref\", \"who\", \"branch_name\",\"_measurement\", \"_field\"])\n  |> sum()\n  |> set(key: \"_field\",value: \"PI8\")\n\n\nunion(tables: [PI4, PI5, PI6, PI7, PI8])\n  |> yield(name: \"lines\")\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PI Bare Commits on Default",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "PI4 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI4\")\n\n\nPI5 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI5\")\n\n\nPI6 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI6\")\n\n\nPI7 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI7\")\n\n\nPI8 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"default\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI8\")\n\n\nunion(tables: [PI4, PI5, PI6, PI7, PI8])\n  |> yield(name: \"lines\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PI Branches without Jira",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "PI4 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"ref\", \"project_id\", \"project\", \"branch\", \"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI4\")\n\n\nPI5 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"ref\", \"project_id\", \"project\", \"branch\", \"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI5\")\n\n\nPI6 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"ref\", \"project_id\", \"project\", \"branch\", \"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI6\")\n\n\nPI7 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"ref\", \"project_id\", \"project\", \"branch\", \"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI7\")\n\n\nPI8 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"ref\", \"project_id\", \"project\", \"branch\", \"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI8\")\n\n\nunion(tables: [PI4, PI5, PI6, PI7, PI8])\n  |> yield(name: \"lines\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PI Merge Requests without Jira",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "PI4 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-09-14T00:00:00Z, stop: 2019-12-14T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"stale\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI4\")\n\n\nPI5 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2019-12-15T00:00:00Z, stop: 2020-03-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"stale\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI5\")\n\n\nPI6 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-03-16T00:00:00Z, stop: 2020-06-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"stale\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI6\")\n\n\nPI7 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-06-16T00:00:00Z, stop: 2020-09-15T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"stale\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI7\")\n\n\nPI8 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"stale\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  |> set(key: \"_field\",value: \"PI8\")\n\n\nunion(tables: [PI4, PI5, PI6, PI7, PI8])\n  |> yield(name: \"lines\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PI Quality Metrics - Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Commits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> distinct(column: \"commit_id\")\n  |> group()\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Commits with Jira",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "pi8jira",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "project_commits",
     "query": "t1 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])    \n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])    \n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n \njoin(tables: {t1: t1, t2: t2}, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> yield(name: \"jira\")",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "default", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "jira", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Committers",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.who != \"Piers Harding [piers@ompka.net]\")   \n  |> drop(columns:[\"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> distinct(column: \"commit_id\")\n  |> group(columns: [\"who\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n:20)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commit Line Changes to Default Branch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"project\", \"project_id\", \"default\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"bare\", \"ref\", \"who\", \"branch_name\",\"_measurement\", \"_field\"])\n  |> sum()\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Bare Commits on default",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])    \n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n\nt2 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])    \n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n \njoin(tables: {t1: t1, t2: t2}, on: [\"default\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> yield(name: \"bare\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bare Commits on default",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-09T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_commits\")\n  |> filter(fn: (r) => r.default == \"1\")\n  |> filter(fn: (r) => r.bare == \"1\")\n  |> drop(columns:[\"commit_id\", \"jira\", \"jira_on_ref\", \"merged\", \"pi\", \"project\", \"project_id\", \"bare\", \"ref\", \"who\", \"branch_name\", \"_measurement\", \"_field\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])    \n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PI Quality Metrics - Branches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total Branches  this PI (excl stale)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"project_id\", \"branch\", \"_measurement\"])\n  |> group()\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Branches this PI with Jira (merged)",
   "type": "gauge",
   "description": "Merged",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nt1 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.jira == \"1\")\n  |> filter(fn: (r) => r.merged == \"True\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"project_id\", \"branch\", \"_measurement\"])\n  |> group()\n  |> count()\n  |> set(key: \"_field\",value: \"PI8\")\n\nt2 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.merged == \"True\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"project_id\", \"branch\", \"_measurement\"])\n  |> group()\n  |> count()\n  |> set(key: \"_field\",value: \"PI8\")\n \njoin(tables: {t1: t1, t2: t2}, on: [\"_field\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> yield(name: \"jira\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Branches with MR This PI",
   "type": "stat",
   "description": "Merged",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"0\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.mr == \"1\")\n  |> filter(fn: (r) => r.merged == \"True\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"project_id\", \"branch\", \"_measurement\"])\n  |> group()\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Stale Branches (> 6 months)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(gitlab_metrics_branches_time_since_last_commit_secs{ref!=\"master\", stale=\"1\"} > 0) by (project, ref)) or vector(0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2000-01-01T00:00:00Z, stop: 2020-12-08T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"project_branches\")\n  |> filter(fn: (r) => r.isstale == \"1\")\n  |> filter(fn: (r) => r.default == \"0\")\n  |> filter(fn: (r) => r.merged == \"False\")\n  |> drop(columns:[\"branch_id\", \"jira\", \"mr\", \"_field\", \"isstale\", \"merged\", \"default\", \"ref\", \"project_id\", \"project\", \"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: count)\n  |> cumulativeSum(columns: [\"_value\"])    \n  |> sort(columns: [\"dateTime\"], desc: false)\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PI Quality Metrics - MRs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total MRs this PI (excl stale)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"stale\", \"_measurement\", \"_field\"])\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Stale Merge Requests (> 4 weeks) this PI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(gitlab_metrics_merge_requests_time_since_created_secs{ref!=\"master\", stale=\"1\"} > 0) by (project, ref, mr)) or vector(0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"1\")\n  |> drop(columns:[\"mr_id\", \"state\", \"stale\", \"author\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"_measurement\", \"_field\"])\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MRs Without Jira",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"stale\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"_measurement\", \"_field\"])\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% MRs without Jira",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nt1 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> filter(fn: (r) => r.jira == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"stale\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"_measurement\", \"_field\"])\n  |> count()\n  |> set(key: \"_field\",value: \"PI8\")\n\nt2 = from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"merge_requests\")\n  |> filter(fn: (r) => r.stale == \"0\")\n  |> drop(columns:[\"mr_id\", \"state\", \"author\", \"stale\", \"jira\", \"project\", \"project_id\", \"merged_by\", \"ref\", \"_measurement\", \"_field\"])\n  |> count()\n  |> set(key: \"_field\",value: \"PI8\")\n \njoin(tables: {t1: t1, t2: t2}, on: [\"_field\"])\n  |> map(fn: (r) => ({ r with _value: (r._value_t1 * 100) / r._value_t2 }))\n  |> yield(name: \"jira\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PI Quality Metrics - Artefacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"projects\" and r._field == \"last_pipeline_duration\")\n  |> drop(columns:[\"pipeline_last_run_status\", \"id\", \"project\", \"_measurement\", \"_field\", \"got_rtd\", \"got_coverage\", \"got_linting\", \"got_tests\"])\n  |> count()\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repositories with RTD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"projects\" and r._field == \"last_pipeline_duration\")\n  |> filter(fn: (r) => r.got_rtd == \"1\")\n  |> drop(columns:[\"pipeline_last_run_status\", \"id\", \"project\", \"_measurement\", \"_field\", \"got_rtd\", \"got_coverage\", \"got_linting\", \"got_tests\"])\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repositories with Linting Badges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"projects\" and r._field == \"last_pipeline_duration\")\n  |> filter(fn: (r) => r.got_linting == \"1\")\n  |> drop(columns:[\"pipeline_last_run_status\", \"id\", \"project\", \"_measurement\", \"_field\", \"got_rtd\", \"got_coverage\", \"got_linting\", \"got_tests\"])\n  |> count()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repositories with Tests Badges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"projects\" and r._field == \"last_pipeline_duration\")\n  |> filter(fn: (r) => r.got_tests == \"1\")\n  |> drop(columns:[\"pipeline_last_run_status\", \"id\", \"project\", \"_measurement\", \"_field\", \"got_rtd\", \"got_coverage\", \"got_linting\", \"got_tests\"])\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repositories with Coverage Badges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"gitlab_metrics\")\n  |> range(start: 2020-09-16T00:00:00Z, stop: 2020-12-16T23:59:59Z)\n  |> filter(fn: (r) => r._measurement == \"projects\" and r._field == \"last_pipeline_duration\")\n  |> filter(fn: (r) => r.got_coverage == \"1\")\n  |> drop(columns:[\"pipeline_last_run_status\", \"id\", \"project\", \"_measurement\", \"_field\", \"got_rtd\", \"got_coverage\", \"got_linting\", \"got_tests\"])\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}