{
 "title": "Ceph - MultiCluster",
 "description": "Ceph Cluster Monitor for multi clusters\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "datacentre",
    "label": "DataCentre",
    "query": {
     "query": "label_values(ceph_mon_quorum_status, datacentre)"
    }
   },
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_mon_quorum_status, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{job=\"$job\", datacentre=\"$datacentre\"}"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_quorum_status{job=\"$job\", datacentre=\"$datacentre\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_bytes_used{job=\"$job\", datacentre=\"$datacentre\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\", datacentre=\"$datacentre\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}/ceph_cluster_total_bytes{job=\"$job\", datacentre=\"$datacentre\"}"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{job=\"$job\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\", datacentre=\"$datacentre\"}) - count(ceph_osd_in{job=\"$job\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{job=\"$job\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\", datacentre=\"$datacentre\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{job=\"$job\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=\"$job\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"$job\", datacentre=\"$datacentre\"})"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ceph_paxos_refresh_latency_sum{job=\"$job\", datacentre=\"$datacentre\"}[1m]))/clamp_min(sum(increase(ceph_paxos_refresh_latency_count{job=\"$job\", datacentre=\"$datacentre\"}[1m])),1)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\", datacentre=\"$datacentre\"}-ceph_cluster_total_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(ceph_osd_op_w{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_rw{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_rw_in_bytes{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "Objects increase Hourly",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ceph_cluster_total_objects{job=\"$job\", datacentre=\"$datacentre\"}[1h]))",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "title": "Capacity increase Hourly",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ceph_cluster_total_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}[1h]))",
     "legendFormat": "Capacity"
    }
   ]
  },
  { "title": "RGW STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "job" },
  {
   "title": "RGW REQUEST",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_req{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "Req"
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_cache_hit{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(irate(ceph_rgw_cache_miss{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "RadosGW QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_get{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(irate(ceph_rgw_put{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "RadosGW ThroughPut",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_get_b{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(irate(ceph_rgw_put_b{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "PUT"
    }
   ]
  },
  { "title": "RocksDB STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }, "repeat": "job" },
  {
   "title": "BlueFS Log Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_bluefs_log_bytes{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "RocksDB GET",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rocksdb_get{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "BlueFS DB %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_bluefs_db_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}/ceph_bluefs_db_total_bytes{job=\"$job\", datacentre=\"$datacentre\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "BlueFS Slow DB %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_bluefs_slow_used_bytes{job=\"$job\", datacentre=\"$datacentre\"}/ceph_bluefs_slow_total_bytes{job=\"$job\", datacentre=\"$datacentre\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "OSD Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\", datacentre=\"$datacentre\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\", datacentre=\"$datacentre\"}[1m])),1)",
     "legendFormat": "read"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\", datacentre=\"$datacentre\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\", datacentre=\"$datacentre\"}[1m])),1)",
     "legendFormat": "write"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\", datacentre=\"$datacentre\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\", datacentre=\"$datacentre\"}[1m])),1)",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "OSD Apply Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Objects Unfound / Degraded / Misplaced",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_num_objects_unfound{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Unfound"
    },
    {
     "expr": "ceph_num_objects_degraded{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_num_objects_misplaced{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Misplaced"
    }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pg_active{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ceph_pg_clean{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Clean"
    },
    {
     "expr": "ceph_pg_peering{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Peering"
    },
    {
     "expr": "ceph_pg_degraded{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_pg_stale{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Stale"
    },
    {
     "expr": "ceph_unclean_pgs{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Unclean"
    },
    {
     "expr": "ceph_pg_undersized{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Undersized"
    },
    {
     "expr": "ceph_pg_incomplete{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "ceph_pg_forced_backfill{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "ceph_pg_inconsistent{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "ceph_pg_forced_recovery{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "ceph_pg_creating{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Creating"
    },
    {
     "expr": "ceph_pg_wait_backfill{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "ceph_pg_deep{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Deep"
    },
    {
     "expr": "ceph_pg_scrubbing{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "ceph_pg_recovering{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Recovering"
    },
    {
     "expr": "ceph_pg_repair{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Repair"
    },
    {
     "expr": "ceph_pg_down{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "ceph_pg_peered{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Peered"
    },
    {
     "expr": "ceph_pg_backfill{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Backfill"
    },
    {
     "expr": "ceph_pg_remapped{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Remapped"
    },
    {
     "expr": "ceph_pg_backfill_toofull{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Faulty PGs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pg_degraded{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_pg_stale{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Stale"
    },
    {
     "expr": "ceph_pg_undersized{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{job=\"$job\", datacentre=\"$datacentre\"}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "OSD Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "OSD Storage Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\", datacentre=\"$datacentre\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\", datacentre=\"$datacentre\"}/ceph_osd_stat_bytes{job=\"$job\", datacentre=\"$datacentre\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}