{
 "title": "Archiver",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "label": "Archiver DB", "query": "mysql" },
   {
    "name": "databaseds",
    "query": "SELECT SUBSTRING_INDEX(SUBSTR(att_name, 9, LENGTH(att_name)),'.',1) FROM att_conf"
   },
   {
    "name": "target_namespace",
    "query": "SELECT SUBSTRING_INDEX(SUBSTR(att_name, 9+LENGTH(\"$databaseds\")+1, LENGTH(att_name)),'.',1) FROM att_conf limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Archiver attribute configurations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Attribute configuration",
   "type": "table",
   "gridPos": { "h": 20, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT att_name, data_type FROM att_conf INNER JOIN att_conf_data_type  ON att_conf.att_conf_data_type_id = att_conf_data_type.att_conf_data_type_id LIMIT 1000"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 20, "w": 3, "x": 15, "y": 1 },
   "targets": [
    { "rawSql": "show tables;" }
   ]
  },
  {
   "title": "Table sizes",
   "type": "table",
   "gridPos": { "h": 20, "w": 5, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    table_name AS `Table`, \r\n    round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB` \r\nFROM information_schema.TABLES \r\nWHERE table_schema = DATABASE();\r\n"
    }
   ]
  },
  { "title": "Attributes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "DevEnum",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devenum_ro INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devenum_ro.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
    }
   ]
  },
  {
   "title": "DevState",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devstate_ro INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devstate_ro.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
    }
   ]
  },
  {
   "title": "Scalar Long64",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devlong64_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devlong64_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
    }
   ]
  },
  {
   "title": "Scalar Long ",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devulong_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devulong_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
    }
   ]
  },
  {
   "title": "Plotly",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired Pointing (time interval)",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 16, "w": 13, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  data_time as time_sec,\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_rw.att_conf_id\r\nWHERE att_conf.att_name = 'tango://$databaseds.$target_namespace.svc.cluster.local:10000/mid_d0001/elt/master/desiredpointing'\r\nAND $__timeFilter(data_time)\r\nORDER BY data_time desc "
      }
     ]
    },
    {
     "title": "Desired Pointing (Latest)",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 16, "w": 11, "x": 13, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_rw.att_conf_id\r\nWHERE att_conf.att_name = 'tango://$databaseds.$target_namespace.svc.cluster.local:10000/mid_d0001/elt/master/desiredpointing'\r\norder by data_time desc\r\nlimit 3"
      }
     ]
    },
    {
     "title": "Achieved Pointing (time interval)",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 16, "w": 13, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  data_time as time_sec,\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_ro INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_ro.att_conf_id\r\nWHERE att_conf.att_name = 'tango://$databaseds.$target_namespace.svc.cluster.local:10000/mid_d0004/elt/master/achievedpointing'\r\nAND $__timeFilter(data_time)\r\nORDER BY data_time desc "
      }
     ]
    },
    {
     "title": "Achieved Pointing (Latest)",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 16, "w": 11, "x": 13, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_ro INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_ro.att_conf_id\r\nWHERE att_conf.att_name = 'tango://$databaseds.$target_namespace.svc.cluster.local:10000/mid_d0004/elt/master/achievedpointing'\r\norder by data_time desc\r\nlimit 3"
      }
     ]
    }
   ]
  }
 ]
}