{
 "title": "Example",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "target_namespace",
    "query": "label_values(read_thread_time, namespace)"
   },
   {
    "name": "devices",
    "query": "label_values(device_attribute{namespace=\"$target_namespace\"}, device)"
   },
   {
    "name": "device",
    "query": "label_values(device_attribute{namespace=\"$target_namespace\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Exporter info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Attributes count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(attribute_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Read attributes count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(attribute_read_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Spectrum attributes count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_attribute_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Image attributes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(image_attribute_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Error attribute count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(error_attr_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(error_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Not managed attributes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(not_managed_attribute_count{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "Read Time (ss)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "read_thread_time{namespace=\"$target_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Read Time (ss)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(read_thread_time{namespace=\"$target_namespace\"})"
    }
   ]
  },
  {
   "title": "DatabaseDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attribute list for device sys/database/2",
     "type": "ska-tango-attribute",
     "description": "Attribute list for device sys/database/2",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\", name=~\"State|Status|StoredProcedureRelease\", namespace=\"$target_namespace\"}  "
      }
     ]
    },
    {
     "title": "Timing average on Databaseds",
     "type": "graph",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_average\", namespace=\"$target_namespace\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing minimum on Databaseds",
     "type": "graph",
     "gridPos": { "h": 13, "w": 10, "x": 10, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_minimum\", namespace=\"$target_namespace\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing calls on Databaseds",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_calls\", namespace=\"$target_namespace\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing maximum on Databaseds",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 10, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_maximum\", namespace=\"$target_namespace\"}",
       "legendFormat": "{{x}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Device View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Float scalar values on $device",
     "type": "graph",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"$device\",dim_x=\"1\",dim_y=\"0\", type=\"float\", namespace=\"$target_namespace\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Attribute list for device $device",
     "type": "ska-tango-attribute",
     "description": "Attribute list for device $device",
     "gridPos": { "h": 25, "w": 11, "x": 11, "y": 7 },
     "targets": [
      {
       "expr": "device_attribute{device=~\"$device\", namespace=\"$target_namespace\"}  "
      }
     ]
    }
   ]
  },
  {
   "title": "Multi-Device View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Float scalar values multi-devices",
     "type": "graph",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=~\"$devices\",dim_x=\"1\",dim_y=\"0\", type=\"float\", namespace=\"$target_namespace\"}",
       "legendFormat": "{{device}} {{name}}"
      }
     ]
    },
    {
     "title": "Attribute list for devices",
     "type": "ska-tango-attribute",
     "gridPos": { "h": 17, "w": 11, "x": 11, "y": 8 },
     "targets": [
      {
       "expr": "device_attribute{device=~\"$devices\", namespace=\"$target_namespace\"}  "
      }
     ]
    }
   ]
  },
  {
   "title": "Tango-Rest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "TANGO Database information",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {}
     ]
    },
    { "title": "$device  - List commands", "type": "ryantxu-ajax-panel", "gridPos": { "h": 12, "w": 11, "x": 12, "y": 57 } }
   ]
  }
 ]
}