{
 "title": "Tango DB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Tango DB", "query": "mysql" }
  ]
 },
 "panels": [
  {
   "title": "Device Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT *\nFROM device " }
   ]
  },
  {
   "title": "IOR clashes",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT count(*), ior\nFROM device \ngroup by ior\nhaving count(*) > 1"
    }
   ]
  },
  {
   "title": "PID clashes",
   "type": "table",
   "gridPos": { "h": 17, "w": 11, "x": 4, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT count(*), pid, host\nFROM device \ngroup by pid, host\nhaving count(*) > 1"
    }
   ]
  },
  {
   "title": "device_history_id Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "select * from device_history_id"
    }
   ]
  },
  {
   "title": "access_device Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 15 },
   "targets": [
    { "rawSql": "select * from access_device" }
   ]
  },
  {
   "title": "Server Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 19 },
   "targets": [
    { "rawSql": "select * from server" }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 21 },
   "targets": [
    { "rawSql": "show tables" }
   ]
  },
  {
   "title": "Event Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 23 },
   "targets": [
    { "rawSql": "SELECT *\nFROM event" }
   ]
  },
  {
   "title": "access_address Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 4, "y": 32 },
   "targets": [
    { "rawSql": "select * from access_address" }
   ]
  },
  {
   "title": "Device Properties",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 36 },
   "targets": [
    { "rawSql": "SELECT *\nFROM property_device" }
   ]
  }
 ]
}