{
 "title": "State analysis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "target_namespace",
    "query": {
     "query": "label_values(read_thread_time, namespace)"
    }
   },
   { "name": "source", "query": "fifemon-graphql-datasource" },
   { "name": "archiver", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "Main View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State, obsState and pointing state",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "device_attribute{name=~\"State|obsState|telescopeState|telescopeHealthState|pointingState\", device=~\"ska_mid/tm_subarray_node/1|mid_csp/elt/subarray_01|mid_sdp/elt/subarray_1|mid_d0001/elt/master|mid_d0002/elt/master|ska_mid/tm_central/central_node\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}/{{name}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 1 },
   "options": {
    "content": "<ul>\n<li>ON = 0</li>\n<li>OFF = 1</li>\n<li>CLOSE = 2</li>\n<li>OPEN = 3</li>\n<li>INSERT = 4</li>\n<li>EXTRACT = 5</li>\n<li>MOVING = 6</li>\n<li>STANDBY = 7</li>\n<li>FAULT = 8</li>\n<li>INIT = 9</li>\n<li>RUNNING = 10</li>\n<li>ALARM = 11</li>\n<li>DISABLE = 12</li>\n<li>UNKNOWN = 13</li>\n</ul>\n\n\n\n\n\n\n"
   }
  },
  {
   "title": "ObsState",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "<ul>\n<li>IDLE = 0</li>\n<li>CONFIGURING = 1</li>\n<li>READY = 2</li>\n<li>SCANNING = 3</li>\n<li>PAUSED = 4</li>\n<li>ABORTED = 5</li>\n<li>FAULT = 6</li>\n</ul>\n\n"
   }
  },
  {
   "title": "PointingState",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "options": {
    "content": "<ul>\n<li>READY = 0</li>\n<li>SLEW = 1</li>\n<li>TRACK = 2</li>\n<li>SCAN = 3</li>\n<li>RESERVED = 4</li>\n</ul>\n\n"
   }
  },
  {
   "title": "State, obsState and pointing state (Archiver)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "(  SELECT    data_time AS \"time\",    att_name,    value_r  \nFROM att_scalar_devenum_ro INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devenum_ro.att_conf_id  \nWHERE    $__timeFilter(data_time)  ORDER BY data_time  )  union \n(  \nSELECT    data_time AS \"time\",    att_name,    value_r  \nFROM att_scalar_devenum_rw \nINNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devenum_rw.att_conf_id  \nWHERE    $__timeFilter(data_time)  \nORDER BY data_time  )\nunion  (  \nSELECT    data_time AS \"time\",    att_name,    value_r  \nFROM att_scalar_devstate_ro INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devstate_ro.att_conf_id  \nWHERE    $__timeFilter(data_time)  \nORDER BY data_time  )"
    }
   ]
  },
  { "title": "State Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Device States",
   "type": "ska-tango-attribute",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "device_attribute{name=\"State\", device=~\"mid_csp/elt/subarray_01|mid_csp_cbf/fspsubarray/01_01|mid_csp_cbf/sub_elt/subarray_01|mid_csp_cbf/vcc/002|mid_csp_cbf/vcc/004|mid_sdp/elt/subarray_1|ska_mid/tm_subarray_node/1\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device with obsState not IDLE",
   "type": "ska-tango-attribute",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 26 },
   "targets": [
    {
     "expr": "device_attribute{name=\"obsState\", str_value!=\"IDLE\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "TM Subarray 1",
   "type": "ska-tango-attribute",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "device_attribute{device=\"ska_mid/tm_subarray_node/1\",name=~\"State|obsState|receptorIDList|activityMessage\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "TM Subarray 1 Activitiy messages",
   "type": "ska-tango-attribute",
   "gridPos": { "h": 23, "w": 9, "x": 9, "y": 39 },
   "targets": [
    {
     "expr": "device_attribute{device=\"ska_mid/tm_subarray_node/1\",name=~\"activityMessage\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Subarrays SDP/CSP",
   "type": "ska-tango-attribute",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"mid_csp/elt/subarray_01||mid_sdp/elt/subarray_1\",name=~\"State|obsState|receptorIDList|activityMessage\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Dishes",
   "type": "ska-tango-attribute",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"mid_d0001/elt/master|mid_d0002/elt/master\",name=~\"State|pointingState\", namespace=\"$target_namespace\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Error logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.namespace: $target_namespace AND ska_severity: ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 73 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.namespace: $target_namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "TANGO Gql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 21, "x": 1, "y": 84 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "device.attributes",
     "endTimePath": "endTime",
     "queryText": "query{device (name:\"sys/tg_test/1\") {\r\n  attributes (pattern:\"*scalar*\") {\r\n    name\r\n    device\r\n    datatype\r\n    dataformat\r\n    writable\r\n    label\r\n    unit\r\n    description\r\n    value\r\n    writevalue\r\n    quality\r\n    timestamp\r\n    displevel\r\n    minvalue\r\n    maxvalue\r\n    minalarm\r\n    maxalarm\r\n    enumLabels\r\n  }\r\n}\r\n}",
     "timePath": "device.attributes.timestamp"
    }
   ]
  }
 ]
}