{
 "title": "iDRAC SNMP DashBoard",
 "description": "A Dashboard for DELL iDRAC based on SNMP_EXPORTER and Prometheus",
 "tags": [
  "snmp",
  "idrac",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Device",
    "query": {
     "query": "query_result(sum by (instance)(globalSystemStatus{job=\"snmp\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "systemFQDN{instance=\"$Device\"}",
     "legendFormat": "{{systemFQDN}}"
    },
    {
     "expr": "systemServiceTag{instance=\"$Device\"}",
     "legendFormat": "{{systemServiceTag}}"
    },
    {
     "expr": "systemExpressServiceCode{instance=\"$Device\"}",
     "legendFormat": "{{systemExpressServiceCode}}"
    },
    {
     "expr": "systemAssetTag{instance=\"$Device\"}",
     "legendFormat": "{{systemAssetTag}}"
    },
    {
     "expr": "systemDataCenterName{instance=\"$Device\"}",
     "legendFormat": "{{systemDataCenterName}}"
    }
   ]
  },
  { "title": "General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "storageStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "globalStorageStatus{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "systemStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "globalSystemStatus{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "systemPowerState",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemPowerState{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "physicalDiskStatus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "physicalDiskComponentStatus{instance=\"$Device\"}\n/ ignoring(physicalDiskName) group_right\nphysicalDiskName",
     "legendFormat": "{{physicalDiskName}}"
    }
   ]
  },
  {
   "title": "Number of logs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "numEventLogEntries{instance=\"$Device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "systemBIOSStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "intrusionStatus{instance=\"$Device\"}\n/ ignoring(intrusionLocationName) group_right\nintrusionLocationName",
     "legendFormat": "{{intrusionLocationName}}"
    }
   ]
  },
  {
   "title": "virtualDiskStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "virtualDiskComponentStatus{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "systemBIOSStatus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "systemBIOSStatus{instance=\"$Device\"}\n/ ignoring(systemBIOSVersionName) group_right\nsystemBIOSVersionName",
     "legendFormat": "{{systemBIOSVersionName}}"
    }
   ]
  },
  { "title": "Detailed Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cooling Device Status",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coolingDeviceStatus{instance=\"$Device\"}\n/ ignoring(coolingDeviceLocationName) group_right\ncoolingDeviceLocationName",
     "legendFormat": "{{coolingDeviceLocationName}}"
    }
   ]
  },
  {
   "title": "PCI Device Status",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pCIDeviceStatus{instance=\"$Device\"}\n/ ignoring(pCIDeviceDescriptionName) group_right\npCIDeviceDescriptionName",
     "legendFormat": "{{pCIDeviceDescriptionName}}"
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "firmwareIndex{instance=\"$Device\"}"
    },
    {
     "expr": "firmwareTypeName{instance=\"$Device\"}"
    },
    {
     "expr": "firmwareVersionName{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "firmwareStatus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "firmwareStatus{instance=\"$Device\"}\n/ ignoring(firmwareTypeName) group_right\nfirmwareTypeName",
     "legendFormat": "{{firmwareTypeName}}"
    }
   ]
  },
  {
   "title": "Power supply input voltage",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "powerSupplyIndex{instance=\"$Device\"}"
    },
    {
     "expr": "powerSupplyLocationName{instance=\"$Device\"}"
    },
    {
     "expr": "powerSupplyCurrentInputVoltage{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "temperatureProbeReading{instance=\"$Device\"}/10\n/ ignoring(temperatureProbeLocationName) group_right\ntemperatureProbeLocationName",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  { "title": "iDRAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "racFirmwareVersion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "racFirmwareVersion{instance=\"$Device\"}",
     "legendFormat": "{{racFirmwareVersion}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memoryDeviceStatus{instance=\"$Device\"}\n/ ignoring(memoryDeviceLocationName) group_right\nmemoryDeviceLocationName",
     "legendFormat": "{{memoryDeviceLocationName}}"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memoryDeviceStatus{instance=\"$Device\"}\n/ ignoring(memoryDeviceLocationName) group_right\nmemoryDeviceLocationName",
     "legendFormat": "{{memoryDeviceLocationName}}"
    }
   ]
  },
  {
   "title": "Memory Information",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "memoryDeviceIndex{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceStateSettings{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceStatus{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceType_info{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceLocationName{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceSize{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceSpeed{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceManufacturerName{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDevicePartNumberName{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceSerialNumberName{instance=\"$Device\"}"
    },
    {
     "expr": "memoryDeviceCurrentOperatingSpeed{instance=\"$Device\"}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Controller Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerRollUpStatus{instance=\"$Device\"}"
    },
    {
     "expr": "controllerComponentStatus{instance=\"$Device\"}"
    },
    {
     "expr": "controllerCacheSizeInMB{instance=\"$Device\"}"
    },
    {
     "expr": "controllerSecurityStatus{instance=\"$Device\"}"
    },
    {
     "expr": "controllerLoadBalanceSetting{instance=\"$Device\"}"
    },
    {
     "expr": "controllerMaxCapSpeed{instance=\"$Device\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Controller rates",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerRebuildRate{instance=\"$Device\"}"
    },
    {
     "expr": "controllerReconstructRate{instance=\"$Device\"}"
    },
    {
     "expr": "controllerPatrolReadRate{instance=\"$Device\"}"
    },
    {
     "expr": "controllerBGIRate{instance=\"$Device\"}"
    },
    {
     "expr": "controllerCheckConsistencyRate{instance=\"$Device\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Controller versions",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerName{instance=\"$Device\"}"
    },
    {
     "expr": "controllerFWVersion{instance=\"$Device\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$Device\"}"
    },
    {
     "expr": "controllerDriverVersion{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Controller Security",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerSecurityStatus{instance=\"$Device\"}"
    },
    {
     "expr": "controllerEncryptionKeyPresent{instance=\"$Device\"}"
    },
    {
     "expr": "controllerEncryptionCapability{instance=\"$Device\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$Device\"}"
    },
    {
     "expr": "controllerT10PICapability{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Controller modes",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controllerPatrolReadMode{instance=\"$Device\"}"
    },
    {
     "expr": "controllerPatrolReadState{instance=\"$Device\"}"
    },
    {
     "expr": "controllerCopyBackMode{instance=\"$Device\"}"
    },
    {
     "expr": "controllerLoadBalanceSetting{instance=\"$Device\"}"
    },
    {
     "expr": "controllerDisplayName{instance=\"$Device\"}"
    },
    {
     "expr": "controllerEnhancedAutoImportForeignConfigMode{instance=\"$Device\"}"
    },
    {
     "expr": "controllerBootModeSupported{instance=\"$Device\"}"
    },
    {
     "expr": "controllerBootMode{instance=\"$Device\"}"
    },
    {
     "expr": "controllerCheckConsistencyMode{instance=\"$Device\"}"
    },
    {
     "expr": "controllerRAID10UnevenSpansSupported{instance=\"$Device\"}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Disk Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "physicalDiskName{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskSpareState{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskComponentStatus{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskSmartAlertIndication{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskPowerState{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskRemainingRatedWriteEndurance{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskOperationalState{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskProgress{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskSecurityStatus{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskState{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Disk Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "physicalDiskName{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskManufacturer{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskSerialNo{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskProductID{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskRevision{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskBusType{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskPartNumber{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskMediaType{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskFormFactor{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskT10PICapability{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskBlockSizeInBytes{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskProtocolVersion{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Disk Speed Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "physicalDiskName{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskBusType{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskNegotiatedSpeed{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskCapableSpeed{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskMediaType{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskProtocolVersion{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskPCIeNegotiatedLinkWidth{instance=\"$Device\"}"
    },
    {
     "expr": "physicalDiskPCIeCapableLinkWidth{instance=\"$Device\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Network Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "networkDeviceIndex{instance=\"$Device\"}"
    },
    {
     "expr": "networkDeviceStatus{instance=\"$Device\"}"
    },
    {
     "expr": "networkDeviceConnectionStatus{instance=\"$Device\"}"
    },
    {
     "expr": "networkDeviceCurrentMACAddress{instance=\"$Device\"}"
    },
    {
     "expr": "networkDevicePermanentMACAddress{instance=\"$Device\"}"
    },
    {
     "expr": "networkDeviceFQDD{instance=\"$Device\"}"
    },
    {
     "expr": "networkDeviceProductName{instance=\"$Device\"}"
    },
    {
     "expr": "networkDeviceVendorName{instance=\"$Device\"}"
    }
   ]
  },
  { "title": "FRU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "FRU Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fruInformationStatus{instance=\"$Device\"}"
    },
    {
     "expr": "fruManufacturerName{instance=\"$Device\"}"
    },
    {
     "expr": "fruSerialNumberName{instance=\"$Device\"}"
    },
    {
     "expr": "fruPartNumberName{instance=\"$Device\"}"
    },
    {
     "expr": "fruRevisionName{instance=\"$Device\"}"
    },
    {
     "expr": "fruFQDD{instance=\"$Device\"}"
    }
   ]
  },
  { "title": "PCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "PCI Information",
   "type": "table",
   "gridPos": { "h": 21, "w": 17, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pCIDeviceIndex{instance=\"$Device\"}"
    },
    {
     "expr": "pCIDeviceStateSettings{instance=\"$Device\"}"
    },
    {
     "expr": "pCIDeviceStatus{instance=\"$Device\"}"
    },
    {
     "expr": "pCIDeviceManufacturerName{instance=\"$Device\"}"
    },
    {
     "expr": "pCIDeviceDescriptionName{instance=\"$Device\"}"
    },
    {
     "expr": "pCIDeviceFQDD{instance=\"$Device\"}"
    }
   ]
  }
 ]
}