{
 "title": "RIELLO UPS (SNMP)",
 "description": "Displays monitoring data collected from Riello uninterruptible power supplies via SNMP.",
 "tags": [
  "riello",
  "ups"
 ],
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysName{job=\"snmp_ups\"}"
    },
    {
     "expr": "sysLocation{job=\"snmp_ups\"}"
    },
    { "expr": "rupsIdentName" },
    { "expr": "rupsIdentModel", "legendFormat": "{{label_name}}" },
    { "expr": "rupsIdentUPSSoftwareVersion" },
    { "expr": "rupsIdentAgentSoftwareVersion" },
    {
     "expr": "sysDescr{job=\"snmp_ups\"}"
    },
    {
     "expr": "sysContact{job=\"snmp_ups\"}"
    }
   ]
  },
  {
   "title": "System Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysUpTime" }
   ]
  },
  {
   "title": "Battery temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rupsBatteryTemperature" }
   ]
  },
  {
   "title": "Battery Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rupsBatteryStatus" }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rupsEstimatedChargeRemaining" }
   ]
  },
  {
   "title": "Alarms Present",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rupsAlarmsPresent" }
   ]
  },
  {
   "title": "Alarm Descriptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "targets": [
    { "expr": "rupsAlarmDescr", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UPS load L1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rupsOutputPercentLoad{rupsOutputLineIndex=\"1\"}",
     "legendFormat": "L{{rupsOutputLineIndex}}"
    }
   ]
  },
  {
   "title": "UPS load L2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rupsOutputPercentLoad{rupsOutputLineIndex=\"2\"}",
     "legendFormat": "L{{rupsOutputLineIndex}}"
    }
   ]
  },
  {
   "title": "UPS load L3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rupsOutputPercentLoad{rupsOutputLineIndex=\"3\"}",
     "legendFormat": "L{{rupsOutputLineIndex}}"
    }
   ]
  },
  {
   "title": "Time spent on battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rupsSecondsOnBattery" }
   ]
  },
  {
   "title": "Autonomy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rupsEstimatedMinutesRemaining*60"
    }
   ]
  },
  {
   "title": "Mains frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rupsInputFrequency/10", "legendFormat": "L{{rupsInputLineIndex}}" }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "rupsBatteryVoltage", "legendFormat": "actual" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "rupsBatteryTemperature", "legendFormat": "Battery Temperature" }
   ]
  },
  {
   "title": "Charge",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rupsEstimatedChargeRemaining", "legendFormat": "Battery Charge" }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "rupsInputVoltage", "legendFormat": "L{{rupsInputLineIndex}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "rupsInputCurrent/10", "legendFormat": "L{{rupsInputLineIndex}}" }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "rupsInputFrequency/10", "legendFormat": "L{{rupsInputLineIndex}}" }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "rupsOutputVoltage", "legendFormat": "L{{rupsOutputLineIndex}}" }
   ]
  },
  {
   "title": "Output load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rupsOutputPercentLoad", "legendFormat": "L{{rupsOutputLineIndex}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "rupsOutputCurrent/10", "legendFormat": "L{{rupsOutputLineIndex}}" }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "rupsOutputFrequency/10", "legendFormat": "L{{rupsOutputLineIndex}}" }
   ]
  },
  { "title": "Bypass", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "rupsBypassVoltage", "legendFormat": "L{{rupsBypassLineIndex}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "rupsBypassCurrent/10", "legendFormat": "L{{rupsBypassLineIndex}}" }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "rupsBypassFrequency/10", "legendFormat": "L{{rupsBypassLineIndex}}" }
   ]
  }
 ]
}