{
 "title": "Versions",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datacentre",
    "query": {
     "query": "label_values(up{job=\"cadvisor\"}, datacentre)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OS/Kernel Versions",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "node_os_version{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_uname_info{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Services Versions",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "container_last_seen{job=\"monitoring\", datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "table",
   "gridPos": { "h": 38, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ceph_mon_metadata{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_mds_metadata{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_mgr_metadata{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_osd_metadata{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_rgw_metadata{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Services Versions",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_container_info{pod=~\"binder-.*|calico-kube-controllers-.*|metallb-controller-.*|ingress-.*|coredns-.*|extdns-.*|gitlab-runner-.*|hub-.*|rook-.*|kube-apiserver-.*|kube\", datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet Version",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "kube_node_info{datacentre=~\"$datacentre\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}